FROM node:22-alpine AS build
WORKDIR /app

COPY Web/package.json ./

RUN npm config set registry https://registry.npmmirror.com \
    && npm install --legacy-peer-deps

COPY Web/ ./

RUN npm run build

FROM nginx:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 80
