import {useBaseApi} from '/@/api/base';

// 出库流水接口服务
export const useWmsExportOrderApi = () => {
	const baseApi = useBaseApi("wmsExportOrder");
	return {
		// 分页查询出库流水
		page: baseApi.page,
		// 查看出库流水详细
		detail: baseApi.detail,
		// 新增出库流水
		add: baseApi.add,
		// 更新出库流水
		update: baseApi.update,
		// 删除出库流水
		delete: baseApi.delete,
		// 删除出库流水
		ExportUndo: baseApi.ExportUndo,
		// 批量删除出库流水
		batchDelete: baseApi.batchDelete,
		// 批量删除出库流水
		IssueOutBound: baseApi.IssueOutBound,
		// 导出出库流水数据
		exportData: baseApi.exportData,
		// 导入出库流水数据
		importData: baseApi.importData,
		// 下载出库流水数据导入模板
		downloadTemplate: baseApi.downloadTemplate,
	}
}

// 出库流水实体
export interface WmsExportOrder {
	// 主键Id
	id: number;
	// 出库流水单据
	exportOrderNo: string;
	// 单据类型
	exportBillType: number;
	// 物料ID
	exportMaterialId: number;
	// 物料编码
	exportMaterialCode: string;
	// 物料名称
	exportMaterialName: string;
	// 物料规格
	exportMaterialStandard: string;
	// 物料型号
	exportMaterialModel: string;
	// 物料类型
	exportMaterialType: string;
	// 物料单位
	exportMaterialUnit: string;
	// 仓库ID
	exportWarehouseId: number;
	// 区域ID
	exportAreaId: number;
	// 储位编码
	exportSlotCode: string;
	// 托盘条码
	exportStockCode: string;
	// 出库数量
	exportQuantity: number;
	// 出库重量
	exportWeight: string;
	// 生产日期
	exportProductionDate: string;
	// 失效日期
	exportLoseDate: string;
	// 部门编码
	exportDepartmentCode: number;
	// 供应商编码
	expotSupplierCode: number;
	// 客户编码
	exportCustomerCode: number;
	// 任务号
	exportTaskNo: string;
	// 执行标志（0待执行、1正在执行、2已完成、3已上传）
	exportExecuteFlag: number;
	// 单据创建时间
	exporOrederDate: string;
	// 备注
	exportRemark: string;
	// 批次
	exportLotNo: string;
	// 出库单据
	exportBillCode: string;
	// 出库序号
	exportListNo: string;
	// 扫码数量
	scanQuantity: number;
	// 扫码人
	scanUserNames: string;
	// 完成时间
	completeDate: string;
	// 拣货数量
	pickedNum: number;
	// 出库单据明细ID
	exportDetailId: number;
	// 箱数
	wholeBoxNum: string;
	// 托盘类型
	outType: number;
	// 托盘总箱数
	stockWholeBoxNum: string;
	// 托盘总数量
	stockQuantity: string;
	// 出库类型，0：正常出库，1：分拣出库，2：转运出库，3：托盘出库,4：备料出库
	exportType: number;
	// 质检状态
	inspectionStatus: number;
	// 软删除
	isDelete?: boolean;
	// 创建时间
	createTime: string;
	// 创建者Id
	createUserId: number;
	// 更新时间
	updateTime: string;
	// 修改者Id
	updateUserId: number;
	// WholeOutWare
	wholeOutWare: string;
	// 根据状态排序
	orderByStatus: number;
	// 储位编码
	exportStockSlotCode: string;
	// 创建者姓名
	createUserName: string;
	// 修改者姓名
	updateUserName: string;
}